// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bundleId/{id}": {
            "delete": {
                "description": "BundleId deletion by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bundleId"
                ],
                "summary": "Delete bundleId",
                "operationId": "delete-bundleId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bundleId identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deletion success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "BundleId not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bundleIds": {
            "get": {
                "description": "Get all bundleIds",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bundleId"
                ],
                "summary": "Get bundleIds list",
                "operationId": "get-bundleIds-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/entities.BundleId"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new bundleId instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bundleId"
                ],
                "summary": "Add new BundleId",
                "operationId": "add-bundleId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "bundleId params",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/d-kv_signer_api_pkg_httpserver_entities.InputCreateBundleId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "commandID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/bundleIds/status/{id}": {
            "post": {
                "description": "Get command status by command id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bundleId"
                ],
                "summary": "Check status",
                "operationId": "get-status-bundleId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/bundleIds/{id}": {
            "get": {
                "description": "Get bundleId instance by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bundleId"
                ],
                "summary": "Get bundleId",
                "operationId": "get-bundleId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bundleId identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.BundleId"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities": {
            "post": {
                "description": "Create new capability instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability"
                ],
                "summary": "Add new capability",
                "operationId": "add-capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "capability params",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/d-kv_signer_api_pkg_httpserver_entities.InputEnableCapability"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "commandID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/status/{id}": {
            "post": {
                "description": "Get command status by command id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability"
                ],
                "summary": "Check status",
                "operationId": "get-status-capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}": {
            "delete": {
                "description": "Capability deletion by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability"
                ],
                "summary": "Delete capability",
                "operationId": "delete-capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "capability identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deletion success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Capability not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/certificates": {
            "get": {
                "description": "Get all certificates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Get certificates list",
                "operationId": "get-certificates-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/entities.Certificate"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new certificate instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Add new certificate",
                "operationId": "add-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "certificate params",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/d-kv_signer_api_pkg_httpserver_entities.InputCreateCertificate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "commandID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/certificates/status/{id}": {
            "post": {
                "description": "Get command status by command id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Check status",
                "operationId": "get-status-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/certificates/{id}": {
            "get": {
                "description": "Get certificate instance by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Get certificate",
                "operationId": "get-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "certificate identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Certificate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Certificate deletion by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Delete certificate",
                "operationId": "delete-certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "certificate identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deletion success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Certificate not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "description": "Get all devices",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Get devices list",
                "operationId": "get-devices-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/entities.Device"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new device instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Add new device",
                "operationId": "add-device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "device params",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Device"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "commandID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/devices/status/{id}": {
            "post": {
                "description": "Get command status by command id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Check status",
                "operationId": "get-status-device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{id}": {
            "get": {
                "description": "Get device instance by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Get device",
                "operationId": "get-device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "device identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Device"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/profiles": {
            "get": {
                "description": "Get all profiles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profiles list",
                "operationId": "get-profiles-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/entities.Profile"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new profile instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Add new profile",
                "operationId": "add-profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "profile params",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Profile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/status/{id}": {
            "post": {
                "description": "Get command status by command id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Check status",
                "operationId": "get-status-profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/{id}": {
            "get": {
                "description": "Get profile instance by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profile",
                "operationId": "get-profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profile identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/pkg_httpserver_handlers.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Profile deletion by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Delete profile",
                "operationId": "delete-profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenantId",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "integrationId",
                        "name": "integrationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profile identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deletion success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Profile not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "d-kv_signer_api_pkg_httpserver_entities.InputCreateBundleId": {
            "type": "object",
            "properties": {
                "bundleId": {
                    "type": "string"
                },
                "bundleName": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "seedId": {
                    "type": "string"
                }
            }
        },
        "d-kv_signer_api_pkg_httpserver_entities.InputCreateCertificate": {
            "type": "object",
            "properties": {
                "certificateType": {
                    "type": "string"
                },
                "csrContent": {
                    "type": "string"
                }
            }
        },
        "d-kv_signer_api_pkg_httpserver_entities.InputEnableCapability": {
            "type": "object",
            "properties": {
                "bundleId": {
                    "type": "string"
                },
                "capabilityType": {
                    "type": "string"
                }
            }
        },
        "entities.BundleId": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CapabilityType"
                    }
                },
                "id": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entities.Certificate": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "entities.Device": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "platform": {
                    "$ref": "#/definitions/entity.Platform"
                },
                "udid": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "entities.Profile": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "entity.CapabilityType": {
            "type": "string",
            "enum": [
                "IN_APP_PURCHASE",
                "PUSH_NOTIFICATIONS",
                "APPLE_PAY",
                "NFC_TAG_READING",
                "APPLE_ID_AUTH"
            ],
            "x-enum-varnames": [
                "InAppPurchase",
                "PushNotifications",
                "ApplePay",
                "NfcTagReading",
                "AppleIdAuth"
            ]
        },
        "entity.Platform": {
            "type": "string",
            "enum": [
                "IOS",
                "MAC_OS"
            ],
            "x-enum-varnames": [
                "Ios",
                "MacOs"
            ]
        },
        "pkg_httpserver_handlers.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/{tenantId}/{integrationId}",
	Schemes:          []string{},
	Title:            "AppStoreConnect project API",
	Description:      "API server for AppStoreConnect project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
