version: '3.8'
services:
  db_command_queue:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=command_queue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes:
      - db_command_queue:/var/lib/postgresql/data

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  db_command_queue:
    driver: local