version: '3.8'
services:
  db_command_queue:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=command_queue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_command_queue:/var/lib/postgresql/data

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data

  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id="my-token"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "my-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_DEV_API_ADDR: "http://localhost:8200"

volumes:
  db:
    driver: local
  db_command_queue:
    driver: local